Repository crew-z/crewz, pull requests merged in 2023-04, with the labels that each got.

#11 feat: header, footer 수정
  src/main/resources/static/assets/css/default.css
  src/main/resources/static/assets/css/main.css
  src/main/resources/templates/include/footer.html
  src/main/resources/templates/include/header.html
Labels: frontend

#12 feat: 메인페이지 작업 및 환경 설정 변경
  src/main/java/environment/project/controller/MainController.java
  src/main/java/environment/project/controller/UserController.java
  src/main/java/environment/project/dto/BoardDTO.java
  src/main/java/environment/project/dto/UserDTO.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/mapper/UserMapper.java
  src/main/java/environment/project/service/BoardService.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/java/environment/project/service/UserService.java
  src/main/java/environment/project/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/assets/css/default.css
  src/main/resources/templates/include/header.html
  src/main/resources/templates/main.html
Labels: backend, frontend, design

#14 feat: DB정보 숨김처리, footer 수정
  src/main/resources/application.properties
  src/main/resources/templates/include/footer.html
Labels: backend, frontend

#17 feat: 동아리 상세페이지 html/css 구조 만들기
  src/main/java/environment/project/controller/BoardController.java
  src/main/resources/static/assets/css/board.css
  src/main/resources/templates/board/board.html
Labels: frontend

#19 feat: 전체동아리 페이지, 검색 기능 추가
  src/main/java/environment/project/controller/MainController.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/service/BoardService.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/resources/static/assets/css/default.css
  src/main/resources/templates/all.html
  src/main/resources/templates/include/header.html
Labels: backend, frontend
