Repository crew-z/crewz, pull requests merged in 2023-06, with the labels that each got.

#120 feat: 검색 결과 페이지 화면 수정, 메인페이지 화면 수정, 폐부된 게시물 미노출
  src/main/java/environment/project/controller/AdminController.java
  src/main/java/environment/project/controller/MainController.java
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/mapper/AdminMapper.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/service/AdminService.java
  src/main/java/environment/project/service/AdminServiceImpl.java
  src/main/resources/templates/admin.html
  src/main/resources/templates/all.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/main.html
Labels: backend, frontend

#122 feat: board 페이지 댓글 권한 변경 & 404에러 페이지
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/controller/BoardReplyController.java
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/dto/BoardCreateDTO.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/service/BoardService.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/assets/css/sign-in.css
  src/main/resources/static/assets/img/404error.svg
  src/main/resources/templates/board.html
  src/main/resources/templates/error/404.html
Labels: backend, frontend

#124 fix: board 페이지 댓글 이름으로 변경
  src/main/java/environment/project/dto/BoardReplyGetDTO.java
  src/main/java/environment/project/mapper/BoardReplyMapper.java
  src/main/resources/templates/board.html
Labels: backend, frontend

#128 fix: 카테고리 디자인 변경
  src/main/resources/static/assets/css/board.css
  src/main/resources/templates/boardCreate.html
  src/main/resources/templates/boardEdit.html
Labels: frontend, design

#130 feat: 회원 가입 유효성 검사, 휴대폰번호 자동 하이픈 추가
  src/main/java/environment/project/controller/SignupController.java
  src/main/resources/templates/signup.html
Labels: backend, frontend

#131 fix: 동아리 합류 버튼 분기 나누기 && 활성화 비활성화 버튼으로 변경
  src/main/resources/static/assets/css/board.css
  src/main/resources/templates/board.html
Labels: frontend

#134 1차 프로젝트 마무리
  src/main/java/environment/project/controller/AdminController.java
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/controller/BoardReplyController.java
  src/main/java/environment/project/controller/MainController.java
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/controller/SignupController.java
  src/main/java/environment/project/dto/BoardCreateDTO.java
  src/main/java/environment/project/dto/BoardReplyGetDTO.java
  src/main/java/environment/project/mapper/AdminMapper.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/mapper/BoardReplyMapper.java
  src/main/java/environment/project/service/AdminService.java
  src/main/java/environment/project/service/AdminServiceImpl.java
  src/main/java/environment/project/service/BoardService.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/assets/css/board.css
  src/main/resources/static/assets/css/sign-in.css
  src/main/resources/static/assets/img/404error.svg
  src/main/resources/templates/admin.html
  src/main/resources/templates/all.html
  src/main/resources/templates/board.html
  src/main/resources/templates/boardCreate.html
  src/main/resources/templates/boardEdit.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/main.html
  src/main/resources/templates/signup.html
Labels: backend, frontend

#137 refactor: 메인화면 수정
  src/main/resources/templates/basicpage.html
Labels: design

#138 feat: docker 환경설정, 메인페이지로 이동 경로 수정
  build.gradle
  src/main/java/environment/project/controller/LoginController.java
  src/main/java/environment/project/controller/MainController.java
  src/main/resources/static/assets/css/main.css
  src/main/resources/templates/basicpage.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/signupSuccess.html
Labels: backend, frontend

#140 fix: board 생성시 카테고리 null에러 해결
  src/main/java/environment/project/controller/BoardController.java
Labels: bug
