Repository crew-z/crewz, pull requests merged in 2023-05, with the labels that each got.

#22 feat: 마이페이지_나의 정보 보기 & 수정
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/dto/ClubDTO.java
  src/main/java/environment/project/dto/ClubInfoDTO.java
  src/main/java/environment/project/dto/UserDTO.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/java/environment/project/service/MypageService.java
  src/main/java/environment/project/service/MypageServiceImpl.java
  src/main/resources/static/assets/vendor/php-email-form/validate.js
  src/main/resources/templates/clubLeaderPage.html
  src/main/resources/templates/mypage/mypageMain.html
  src/main/resources/templates/mypageMain.html
Labels: backend, frontend

#26 feat: 로그인/회원가입/회원가입완료 페이지 구현
  build.gradle
  src/main/java/environment/project/controller/LoginController.java
  src/main/java/environment/project/controller/MainController.java
  src/main/java/environment/project/controller/SignupController.java
  src/main/java/environment/project/dto/UserDTO.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/mapper/UserMapper.java
  src/main/java/environment/project/service/BoardService.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/java/environment/project/service/UserService.java
  src/main/java/environment/project/service/UserServiceImpl.java
  src/main/resources/static/assets/css/default.css
  src/main/resources/static/assets/css/sign-in.css
  src/main/resources/static/assets/vendor/bootstrap/css/bootstrap.min.css
  src/main/resources/templates/include/header.html
  src/main/resources/templates/login.html
  src/main/resources/templates/loginForm.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/signupSuccess.html
Labels: backend, frontend

#27 feat: 메인페이지 수정, board 메서드 추가
  src/main/java/environment/project/controller/AdminController.java
  src/main/java/environment/project/dto/BoardDTO.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/service/BoardService.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/resources/static/assets/css/default.css
  src/main/resources/static/assets/img/banner/yellowBanner.png
  src/main/resources/templates/assets/img/features-1.svg
  src/main/resources/templates/assets/img/features-2.svg
  src/main/resources/templates/assets/img/features-3.svg
  src/main/resources/templates/assets/img/features-4.svg
  src/main/resources/templates/assets/img/features-5.svg
  src/main/resources/templates/assets/img/features-6.svg
  src/main/resources/templates/include/footer.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/main.html
  src/test/java/environment/project/service/BoardServiceImplTest.java
Labels: backend, frontend

#33 feat: 동아리 상세 페이지 로직(C,R,U) 설계 완료
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/dto/BoardCreateDTO.java
  src/main/java/environment/project/dto/BoardUpdateDTO.java
  src/main/java/environment/project/exception/GlobalExceptionHandler.java
  src/main/java/environment/project/exception/ResourceNotFoundException.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/service/BoardService.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/resources/static/assets/css/board.css
  src/main/resources/templates/board.html
  src/main/resources/templates/board/board.html
  src/main/resources/templates/boardCreate.html
  src/main/resources/templates/boardEdit.html
  src/main/resources/templates/error/404.html
Labels: backend, frontend

#37 feat: 메인페이지 수정
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/controller/MainController.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/resources/templates/main.html
Labels: backend

#40 feat: 동아리장 마이페이지_동아리 신청회원 조회
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/java/environment/project/service/MypageService.java
  src/main/java/environment/project/service/MypageServiceImpl.java
  src/main/resources/templates/clubLeaderPage.html
Labels: backend, frontend

#42 feat: 메인페이지 수정,관리자 기능 추가
  src/main/java/environment/project/controller/AdminController.java
  src/main/java/environment/project/mapper/ClubApplyMapper.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/java/environment/project/service/ClubApplyService.java
  src/main/java/environment/project/service/ClubApplyServiceImpl.java
  src/main/resources/static/assets/css/default.css
  src/main/resources/static/assets/vendor/bootstrap/css/bootstrap.min.css
  src/main/resources/templates/admin.html
  src/main/resources/templates/all.html
Labels: backend, frontend

#43 feat: 동아리장 마이페이지_동아리 신청회원 조회
  src/main/java/environment/project/controller/MainController.java
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/java/environment/project/service/MypageService.java
  src/main/java/environment/project/service/MypageServiceImpl.java
  src/main/resources/templates/include/header.html
Labels: backend

#46 feat: 동아리 개설 신청 페이지
  src/main/java/environment/project/controller/ClubApplyController.java
  src/main/java/environment/project/controller/LoginController.java
  src/main/java/environment/project/controller/MainController.java
  src/main/java/environment/project/controller/SignupController.java
  src/main/java/environment/project/mapper/ClubApplyMapper.java
  src/main/java/environment/project/mapper/UserMapper.java
  src/main/java/environment/project/service/ClubApplyService.java
  src/main/java/environment/project/service/ClubApplyServiceImpl.java
  src/main/java/environment/project/service/UserService.java
  src/main/java/environment/project/service/UserServiceImpl.java
  src/main/resources/static/assets/css/club-apply.css
  src/main/resources/static/assets/js/main.js
  src/main/resources/templates/include/header.html
  src/main/resources/templates/newclub.html
  src/main/resources/templates/signup.html
Labels: backend, frontend

#47 feat: 동아리 댓글 로직 설계 완료
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/controller/BoardReplyController.java
  src/main/java/environment/project/dto/BoardGetDTO.java
  src/main/java/environment/project/dto/BoardReplyCreateDTO.java
  src/main/java/environment/project/dto/BoardReplyGetDTO.java
  src/main/java/environment/project/dto/BoardReplyUpdateDTO.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/mapper/BoardReplyMapper.java
  src/main/java/environment/project/service/BoardReplyService.java
  src/main/java/environment/project/service/BoardReplyServiceImpl.java
  src/main/java/environment/project/service/BoardService.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/java/environment/project/util/BoardUtil.java
  src/main/java/environment/project/util/DateUtil.java
  src/main/resources/static/assets/css/board.css
  src/main/resources/templates/board.html
  src/main/resources/templates/boardEdit.html
Labels: backend, frontend

#49 feat: 로그인된 유저로 동아리장 페이지 운영
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/dto/ClubDTO.java
  src/main/java/environment/project/dto/ClubInfoDTO.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/java/environment/project/service/MypageService.java
  src/main/java/environment/project/service/MypageServiceImpl.java
  src/main/resources/templates/clubLeaderPage.html
  src/main/resources/templates/mypageMain.html
Labels: backend

#50 feat: 관리자 기능 추가
  src/main/java/environment/project/controller/AdminController.java
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/dto/ClubInfoDTO.java
  src/main/java/environment/project/mapper/AdminMapper.java
  src/main/java/environment/project/mapper/ClubApplyMapper.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/java/environment/project/service/AdminService.java
  src/main/java/environment/project/service/AdminServiceImpl.java
  src/main/java/environment/project/service/MypageService.java
  src/main/resources/templates/admin.html
Labels: backend, frontend

#51 feat: 동아리 개설 신청 페이지 구현
  src/main/java/environment/project/controller/ClubApplyController.java
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/service/MypageServiceImpl.java
  src/main/resources/static/assets/css/default.css
  src/main/resources/templates/include/header.html
  src/main/resources/templates/newclub.html
  src/main/resources/templates/newclubResult.html
  src/main/resources/templates/newclubView.html
Labels: backend, frontend

#53 feat: 유저 마이페이지 동아리 분리
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/java/environment/project/service/MypageService.java
  src/main/java/environment/project/service/MypageServiceImpl.java
  src/main/resources/templates/clubLeaderPage.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/mypageMain.html
Labels: backend, frontend

#55 feat: 유저 마이페이지 리뷰작성 버튼
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/java/environment/project/service/MypageService.java
  src/main/java/environment/project/service/MypageServiceImpl.java
  src/main/resources/templates/clubLeaderPage.html
  src/main/resources/templates/mypageMain.html
Labels: backend

#58 feat: 로그인 세션으로 값 변경, 동아리 합류 기능 추가
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/controller/BoardReplyController.java
  src/main/java/environment/project/controller/ClubInfoController.java
  src/main/java/environment/project/dto/BoardCreateDTO.java
  src/main/java/environment/project/dto/BoardGetDTO.java
  src/main/java/environment/project/dto/BoardPeriodGetDTO.java
  src/main/java/environment/project/dto/BoardReplyCreateDTO.java
  src/main/java/environment/project/dto/BoardReplyGetDTO.java
  src/main/java/environment/project/dto/BoardReplyUpdateDTO.java
  src/main/java/environment/project/dto/BoardUpdateDTO.java
  src/main/java/environment/project/dto/ClubInfoCreateDTO.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/mapper/BoardReplyMapper.java
  src/main/java/environment/project/mapper/ClubInfoMapper.java
  src/main/java/environment/project/service/BoardReplyService.java
  src/main/java/environment/project/service/BoardReplyServiceImpl.java
  src/main/java/environment/project/service/BoardService.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/java/environment/project/service/ClubInfoService.java
  src/main/java/environment/project/service/ClubInfoServiceImpl.java
  src/main/java/environment/project/util/BoardUtil.java
  src/main/java/environment/project/util/DateUtil.java
  src/main/resources/templates/board.html
  src/main/resources/templates/boardCreate.html
  src/main/resources/templates/boardEdit.html
Labels: backend, frontend

#59 feat: 마이페이지 동아리장페이지
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/dto/ClubApplyDTO.java
  src/main/java/environment/project/dto/ClubNameDTO.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/java/environment/project/service/MypageService.java
  src/main/java/environment/project/service/MypageServiceImpl.java
  src/main/resources/static/assets/css/main.css
  src/main/resources/templates/clubLeaderPage.html
  src/main/resources/templates/mypageMain.html
Labels: backend, frontend

#60 bug: 로그인 유효성 검사 추가 구현
  src/main/java/environment/project/controller/LoginController.java
  src/main/java/environment/project/service/UserService.java
  src/main/java/environment/project/service/UserServiceImpl.java
  src/main/resources/static/assets/css/default.css
  src/main/resources/templates/login.html
  src/main/resources/templates/newclub.html
  src/main/resources/templates/newclubResult.html
  src/main/resources/templates/newclubView.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/signupSuccess.html
Labels: bug, backend

#63 fix: 동아리장페이지 이슈해결
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/resources/templates/mypageMain.html
Labels: backend, frontend

#65 feat: 마이페이지 게시물 등록 버튼 추가
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/dto/ClubApplyDTO.java
  src/main/java/environment/project/mapper/BoardReplyMapper.java
  src/main/java/environment/project/mapper/ClubInfoMapper.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/resources/static/assets/css/board.css
  src/main/resources/templates/board.html
  src/main/resources/templates/module/commonCss.html
  src/main/resources/templates/mypageMain.html
Labels: backend, frontend

#67 fix: 관리자 페이지 버그 픽스
  src/main/resources/templates/admin.html
Labels: bug, frontend

#69 feat: 테스트 후 피드백 개선 진행
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/mapper/BoardReplyMapper.java
  src/main/java/environment/project/mapper/ClubInfoMapper.java
  src/main/java/environment/project/service/BoardService.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/resources/static/assets/css/board.css
  src/main/resources/templates/board.html
  src/main/resources/templates/boardCreate.html
  src/main/resources/templates/boardEdit.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/module/commonJs.html
Labels: backend, frontend

#71 feat: 게시물 수정 파라메터 변경
  src/main/resources/templates/mypageMain.html
Labels: backend

#73 feat: board 생성, 수정시 clubNo, boardNo 받아오는지 확인
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/resources/templates/board.html
Labels: backend, frontend

#77 fix: 마이페이지 nav바 수정
  src/main/resources/templates/clubLeaderPage.html
  src/main/resources/templates/mypageMain.html
Labels: frontend

#78 style: main, header CSS 수정
  src/main/resources/static/assets/css/default.css
  src/main/resources/static/assets/css/main.css
  src/main/resources/static/assets/img/crewz-logo.png
  src/main/resources/templates/include/header.html
  src/main/resources/templates/main.html
Labels: frontend

#79 feat: board 카운팅 추가, mapper 쿼리 수정 및 주석 제거
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/mapper/BoardReplyMapper.java
  src/main/java/environment/project/mapper/ClubInfoMapper.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/resources/static/assets/css/board.css
  src/main/resources/templates/board.html
  src/main/resources/templates/boardCreate.html
  src/main/resources/templates/boardEdit.html
Labels: backend, frontend

#80 feat: 메인페이지 card, 목록 조회, 모든 동아리 기능 모집 태그 추가
  src/main/java/environment/project/controller/MainController.java
  src/main/resources/static/assets/css/default.css
  src/main/resources/templates/all.html
  src/main/resources/templates/main.html
Labels: backend, frontend

#81 design: css 1차 최종 변경
  src/main/resources/static/assets/css/board.css
  src/main/resources/templates/board.html
Labels: design

#86 feat: 메인페이지 리스트 쿼리 수정
  src/main/java/environment/project/controller/MainController.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/service/BoardService.java
  src/main/java/environment/project/service/BoardServiceImpl.java
  src/main/resources/templates/all.html
  src/main/resources/templates/main.html
Labels: backend, frontend

#89 feat: 메인페이지 리스트 쿼리 수정
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/resources/templates/all.html
  src/main/resources/templates/main.html
Labels: backend, frontend

#91 feat: 마이페이지 css 수정
  src/main/resources/templates/mypageMain.html
Labels: frontend

#93 fix: 마이페이지 게시물 등록 버튼
  src/main/resources/static/assets/css/default.css
  src/main/resources/templates/mypageMain.html
Labels: bug

#97 feat: board상세페이지 리뷰 수정 권한 추가 및 로그인여부에 작성 권한 추가
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/dto/BoardReplyWithMetadata.java
  src/main/resources/static/assets/css/board.css
  src/main/resources/templates/board.html
Labels: backend, frontend

#99 feat: 마이페이지, 관리자 페이지 footer 위치 수정
  src/main/resources/templates/admin.html
  src/main/resources/templates/clubLeaderPage.html
  src/main/resources/templates/mypageMain.html
Labels: frontend

#100 feat: board상세페이지 리뷰 수정 권한 추가
  src/main/java/environment/project/controller/BoardController.java
Labels: backend, frontend

#102 refactor: 배포를 위한 header,footer,css 경로 수정
  build.gradle
  src/main/java/environment/project/configuration/MvcConfiguration.java
  src/main/java/environment/project/controller/ClubApplyController.java
  src/main/java/environment/project/mapper/BoardMapper.java
  src/main/java/environment/project/mapper/UserMapper.java
  src/main/resources/templates/admin.html
  src/main/resources/templates/all.html
  src/main/resources/templates/board.html
  src/main/resources/templates/boardCreate.html
  src/main/resources/templates/boardEdit.html
  src/main/resources/templates/clubLeaderPage.html
  src/main/resources/templates/include/footer.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/module/common-css.html
  src/main/resources/templates/module/commonCss.html
  src/main/resources/templates/module/commonJs.html
  src/main/resources/templates/mypageMain.html
  src/main/resources/templates/newclub.html
  src/main/resources/templates/newclubResult.html
  src/main/resources/templates/newclubView.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/signupSuccess.html
Labels: backend

#105 debug: 로그 추가
  src/main/java/environment/project/controller/AdminController.java
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/controller/BoardReplyController.java
  src/main/java/environment/project/controller/LoginController.java
  src/main/java/environment/project/controller/MypageController.java
  src/main/resources/templates/newclubView.html
Labels: backend

#108 feat: 카테고리 기능 추가
  src/main/java/environment/project/controller/BoardController.java
  src/main/java/environment/project/dto/BoardCategoryDTO.java
  src/main/java/environment/project/dto/BoardCreateDTO.java
  src/main/java/environment/project/dto/BoardUpdateDTO.java
  src/main/java/environment/project/dto/CategoryInfoDTO.java
  src/main/java/environment/project/mapper/CategoryInfoMapper.java
  src/main/java/environment/project/service/CategoryInfoService.java
  src/main/java/environment/project/service/CategoryInfoServiceImpl.java
  src/main/resources/templates/board.html
  src/main/resources/templates/boardCreate.html
  src/main/resources/templates/boardEdit.html
Labels: backend, frontend

#115 feat: 동아리장페이지 동아리원 리스트 조회
  build.gradle
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/resources/templates/clubLeaderPage.html
  src/main/resources/templates/module/commonJs.html
  src/main/resources/templates/mypageMain.html
Labels: bug, backend

#116 feat: 동아리장페이지 동아리원 리스트 조회
  build.gradle
  src/main/java/environment/project/controller/MypageController.java
  src/main/java/environment/project/mapper/MypageMapper.java
  src/main/resources/templates/clubLeaderPage.html
  src/main/resources/templates/module/commonJs.html
  src/main/resources/templates/mypageMain.html
Labels: backend
